/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#bffeff",
        "secondary": "#006668",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#eff8fe",
        "tertiary": "#2c6900",
        "background": "#eff8fe",
        "surface": "#eff8fe",
        "on-tertiary-fixed-variant": "#2b6600",
        "surface-container-low": "#e8f2f9",
        "inverse-surface": "#070f13",
        "tertiary-container": "#75fd00",
        "primary-dim": "#005578",
        "on-secondary-fixed-variant": "#006668",
        "on-tertiary-container": "#265c00",
        "secondary-fixed-dim": "#00ecef",
        "on-tertiary": "#d6ffb8",
        "secondary-dim": "#00595b",
        "outline": "#6f787d",
        "on-secondary-container": "#005b5d",
        "on-primary-fixed-variant": "#003e58",
        "on-error": "#ffefee",
        "tertiary-fixed-dim": "#6ded00",
        "on-primary-fixed": "#001a28",
        "error-container": "#fb5151",
        "secondary-container": "#0bfbff",
        "outline-variant": "#a5aeb4",
        "primary-container": "#2dbcfe",
        "secondary-fixed": "#0bfbff",
        "on-primary": "#e8f4ff",
        "tertiary-fixed": "#75fd00",
        "on-background": "#273034",
        "inverse-on-surface": "#959ea4",
        "error": "#b31b25",
        "tertiary-dim": "#265b00",
        "surface-container-highest": "#d1dfe7",
        "primary-fixed": "#2dbcfe",
        "on-surface": "#273034",
        "on-secondary-fixed": "#004748",
        "surface-tint": "#006289",
        "inverse-primary": "#2dbcfe",
        "surface-variant": "#d1dfe7",
        "surface-container": "#dfeaf1",
        "error-dim": "#9f0519",
        "primary-fixed-dim": "#02aeef",
        "surface-container-high": "#d8e4ec",
        "on-surface-variant": "#545d62",
        "surface-dim": "#c8d7df",
        "on-primary-container": "#00344b",
        "on-tertiary-fixed": "#1c4700",
        "on-error-container": "#570008",
        "primary": "#006289"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
